module.exports = [
    {
        'name': 'Angelic Mandarin',
        'ico': 'AngelicMandarin.png',
        'cost': 3,
        'attack': 1,
        'health': 5,
    },
    {
        name: 'Blinding Reflector',
        ico: 'BlindingReflector.png',
        cost: 4,
        attack: 2,
        health: 4,
    },
    {
        name: 'Carrion Shade',
        ico: 'CarrionShade.png',
        cost: 3,
        attack: 1,
        health: 4,
    },
    {
        name: 'Celestial Harpy',
        ico: 'CelestialHarpy.png',
        cost: 3,
        attack: 1,
        health: 3,
    },
    {
        name: 'Chaos Agent',
        ico: 'ChaosAgent.png',
        cost: 1,
        attack: 1,
        health: 2,
    },
    {
        name: 'Chaos Knight',
        ico: 'ChaosKnight.png',
        cost: 5,
        attack: 2,
        health: 4,
    },
    {
        name: 'Deeplurker',
        ico: 'Deeplurker.png',
        cost: 2,
        attack: 1,
        health: 2,
    },
    {
        name: 'Dhampir Stalker',
        ico: 'DhampirStalker.png',
        cost: 4,
        attack: 1,
        health: 5,
    },
    {
        name: 'Diemonshark',
        ico: 'Diemonshark.png',
        cost: 6,
        attack: 3,
        health: 6,
    },
    {
        name: 'Flying Squid',
        ico: 'FlyingSquid.png',
        cost: 8,
        attack: 2,
        health: 7,
    },
    {
        name: 'Gargoya Scrapper',
        ico: 'GargoyaScrapper.png',
        cost: 1,
        attack: 1,
        health: 2,
    },
    {
        name: 'Kelya Frendul',
        ico: 'KelyaFrendul.png',
        cost: 4,
        attack: 2,
        health: 2,
    },
    {
        name: 'Life Sapper',
        ico: 'LifeSapper.png',
        cost: 3,
        attack: 1,
        health: 2,
    },
    {
        name: 'Merdaali Guardian',
        ico: 'MerdaaliGuardian.png',
        cost: 3,
        attack: 2,
        health: 3,
    },
    {
        name: 'Mycelic Morphoid',
        ico: 'MycelicMorphoid.png',
        cost: 1,
        attack: 1,
        health: 2,
    },
    {
        name: 'Obsidian',
        ico: 'Obsidian.png',
        cost: 4,
        attack: 4,
        health: 1,
    },
    {
        name: 'Pelacor Arbalest',
        ico: 'PelacorArbalest.png',
        cost: 6,
        attack: 4,
        health: 6,
    },
    {
        name: 'River Nymph',
        ico: 'RiverNymph.png',
        cost: 4,
        attack: 1,
        health: 5,
    },
    {
        name: 'Scavo Hireling',
        ico: 'ScavoHireling.png',
        cost: 3,
        attack: 2,
        health: 1,
    },
    {
        name: 'Time Mage',
        ico: 'TimeMage.png',
        cost: 4,
        attack: 1,
        health: 3,
    },
    {
        name: 'Venari Knifer',
        ico: 'VenariKnifer.png',
        cost: 6,
        attack: 2,
        health: 7,
    },
    {
        name: 'Venari Scout',
        ico: 'VenariScout.png',
        cost: 3,
        attack: 1,
        health: 3,
    },
    {
        name: 'Xenith Archer',
        ico: 'XenithArcher.png',
        cost: 2,
        attack: 1,
        health: 2,
    }
]